### ISSUE TITLE
CurveHash API is broken in v4.5.18

### ISSUE THREAD

**Issue by RainbowMiner** [rplant8/cpuminer-opt-rplant#10]
The current release's API reports way(!) to high hashrates for curvehash (we get numbers in GH, where we would expect kH)
Please check.
I am using Windows10.

**Comment by Quake4** [comment]
4.5.20 same

**Comment by rplant8** [comment]
curvehash initially has a broken wallet. I try to bring hashrates to a common denominator, but one thing leads to another and everything falls apart. I believe that the wallet and algo are crooked, so well, don't give a fuck. all the same soon the GPU will come

**Comment by rplant8** [comment]
oblivion developers made a bad wallet, the owners of curvehash copied it. I warned them.

**Comment by rplant8** [comment]
I think it's better to throw algo out of the miner than to build a bunch of crutches in the miner and pool for the sake of one wrong wallet

**Comment by RainbowMiner** [comment]
Thank you for your comments on CurveHash. I will better leave that algo deactivated for now.
