### ISSUE TITLE
stratum connection failed on 5.0.5 and 5.0.6

### ISSUE THREAD

**Issue by Quake4** [rplant8/cpuminer-opt-rplant#13]
![image](https://user-images.githubusercontent.com/29517243/102813582-205f9a80-43da-11eb-8c2c-06e929821865.png)

**Comment by rplant8** [comment]
full cli?

**Comment by Quake4** [comment]
`cpuminer-avx2.exe -a cpupower -o stratum+tcp://cpupower.eu.mine.zpool.ca:6240 -u xxx -p c=BTC,Home -q -b 4048 --cpu-priority 1 --retry-pause 5 -T 500`

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/102880758-e5eb1180-445c-11eb-8865-233f419390d8.png)

**Comment by rplant8** [comment]
add --no-doh key
I will understand why DoH does not work under windows
