### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by maribun20** [rplant8/cpuminer-opt-rplant#15]
hello sir can you help me to build cpu miner for windows, but i don't have my own computer. and I just built it on Ubuntu without having any special Windows software.
so I asked for his help (just build it without changing the original environment).
because now I have become a cpuminer software developer from tpruvot's repository.
and have succeeded in adding several algorithms for cpu such as the yespower variant.
If the software allready compiled in to windows binaries, you can send the software link to my gmail = maribun23@gmail.com.
for the software link below.
https://github.com/maribun20/termux-miner/releases/download/2.6.4/termux-miner-2.6.4.tar.gz

**Comment by rplant8** [comment]
use mingw32

**Comment by maribun20** [comment]
Okay thanks...

Pada tanggal Kam, 21 Jan 2021 20.15, rplant8 <notifications@github.com>
menulis:
