### ISSUE TITLE
cpuminer-sse2 : Failed to get extraonce2_size

### ISSUE THREAD

**Issue by takeruadelbert** [rplant8/cpuminer-opt-rplant#16]
Hi, I have a problem when running `cpuminer-sse2`

![image](https://user-images.githubusercontent.com/17585173/106384080-e4b5e880-63fb-11eb-9d8b-e8ae2184fedd.png)

btw this is full command line I did use:
```
./cpuminer-sse2 -a yespower -o stratum+tcp://daggerhashimoto.usa.nicehash.com:3353 -u xxx -p xxx -t1 --no-doh
```

_P.S. I added `--no-doh` key for preventing error `Stratum Connection Failed`._

any solution for this?
thanks

**Comment by rplant8** [comment]
where did you find yespower on nicehash?

**Comment by takeruadelbert** [comment]
@rplant8 so the problem is the algo param? could you tell me the list of available algo? I couldn't find your documentation.

**Comment by takeruadelbert** [comment]
@rplant8 it's mismatch algo param apparrently, I change it yto `neoscrypt` and it runs now.
it'd be much appreciated if you could tell the list of available algorithm.
