### ISSUE TITLE
Segmentation fault on macOS Big Sur (gr algo)

### ISSUE THREAD

**Issue by goldmont** [rplant8/cpuminer-opt-rplant#17]
Hi,

the latest release, which includes gr algorithm, crashes after a few seconds on macOS Big Sur. Thank you for your efforts.

**Comment by ivanov-vision** [comment]
Hello!

So, I have I think the same issue.
HiveOS (latest)
Rplant (latest)
i7-8700k
32GB ram ddr4 3200

I am trying to run cpuminer-opt-rplant 5. ... ( latest version ) to mine RTM in my HiveOS as my CPU is sitting idle anyway.
I have the following issues:

While setting up through my HiveOS portal, my miner log is showing: Exited code 0, waiting to cooldown a bit

While trying to run through the shell h-run.sh it shows me avx2 not found file or dir

While trying to run cpuminer-avx2 straight I get segmentation fault, core dump 

I did try with the previous version of Hive and Rplant but no luck.

**Comment by rplant8** [comment]
I'll test it next week, I don't have a computer with bigsug yet
