### ISSUE TITLE
--pass=m=solo

### ISSUE THREAD

**Issue by eltech35** [rplant8/cpuminer-opt-rplant#37]
Can't solo mine using password "m=solo"

Tried 
--pass=m=solo
--pass="m=solo"
--pass='m=solo'
--pass=`m=solo`
 same with -p
always switched by -p x at runtime (looking with ps aux)

**Comment by rplant8** [comment]
-p m=solo

**Comment by eltech35** [comment]
tried that but "ps aux" tells me it's still replaced by -p x
 
<img width="1373" alt="Capture d’écran 2022-01-08 à 16 29 13" src="https://user-images.githubusercontent.com/37953242/148650035-b3310c35-7d55-4567-92e8-f7b20bba9d1e.png">

**Comment by rplant8** [comment]
Are you running it through a script? You need to fix it in the script itself.

**Comment by eltech35** [comment]
yep, made a script, modified the script with -p m=solo, same issue, even running it direct from command line and ps aux from another term session, ps aux tells me it uses -p x

**Comment by rplant8** [comment]
show sh file

**Comment by eltech35** [comment]
cat avian.sh 
./cpuminer-ryzen -a minotaurx -o stratum+tcps://stratum-eu.rplant.xyz:17068 -u RSFSaAp4m4atajNRJV7WpJb5fCZxMqTJfM.m2051 -p m=solo --threads=30 --api-bind 127.0.0.1:4069

**Comment by rplant8** [comment]
the script is correct. look for where -p x comes from
it looks like you're running a different script

**Comment by eltech35** [comment]
Very weird

**Comment by rplant8** [comment]
It's not a bug in the miner, you're calling it incorrectly somewhere

**Comment by eltech35** [comment]
After 24h, pool side, rig is showed with correct hashrate and immature/balance/shares to 0, so i came to the conclusion it is actually solo mining. Have to deduct when you "ps aux" from command line, the password p=x showed in the process line is here to obfuscate the password...simply.

Would be cool if pool.rplant.xyz could implement an "S" or "SOLO" in Workers tab for workers detected mining solo.

Thanks for your help @rplant8
