### ISSUE TITLE
Algorihm

### ISSUE THREAD

**Issue by maribun20** [rplant8/cpuminer-opt-rplant#4]
hello sir... 
Please add m7m algorithm in file cpuminer-opt-linux.tar.gz
Thank you.....

**Comment by rplant8** [comment]
I make a miner for my pool's coins. On algo m7m I only know magi, I don't see a profit there

**Comment by maribun20** [comment]
in your opinion which coins are the most profitable for cpu ... ???

**Comment by maribun20** [comment]
And what name of your pools..??
Can me join for your pools...?

**Comment by maribun20** [comment]
What your pool support with auto exchange....?
Example me mining myriad coins with yescrypt algorithm and my wallet adress
I use doge coin adress for payout curency can or not....?

Pada tanggal Sel, 18 Agt 2020 06.54, rplant8 <notifications@github.com>
menulis:
