### ISSUE TITLE
Issue on mac build

### ISSUE THREAD

**Issue by arminmacx** [rplant8/cpuminer-opt-rplant#54]
Hi,

thanks for building macos version but there are an issues on that build.

i tried to use the cpuminer-aes avx2 avx & sse42 but none of them working as i get  :
```
segmentation fault
```
and only one which can be run is cpuminer-sse but that one cannot connect to the pool and give this :
```
Stratum connection failed:
```
i already allowed the miner on privacy section of the mac so i can run them but im still out of luck i can only run your miner using windows build on crossover fine on mac.

Can you check your build again?

thanks for your hard work

**Comment by rplant8** [comment]
mac model and os version?

**Comment by arminmacx** [comment]
iMac + macos sonoma

**Comment by rplant8** [comment]
iMac model?

**Comment by arminmacx** [comment]
imac20,2 with i9-10900K

**Comment by rplant8** [comment]
I got sse2 working. the other versions are really inoperable. i will fix it in the next version.
use 5.0.29

**Comment by rplant8** [comment]
fixed
re-download the release
