### ISSUE TITLE
macbook pro. Stratum connection failed 

### ISSUE THREAD

**Issue by 544325999** [rplant8/cpuminer-opt-rplant#56]
<img width="592" alt="image" src="https://github.com/rplant8/cpuminer-opt-rplant/assets/30817982/ed64deab-40a1-43d3-a441-ca2fb3a040cf">

ping is ok
<img width="583" alt="image" src="https://github.com/rplant8/cpuminer-opt-rplant/assets/30817982/d30a3933-1102-46ee-b381-8a325d8ae9ec">

**Comment by rplant8** [comment]
This miner is not a commercial product, I make it only to support my pool. work with other pools is not guaranteed or supported.
